# Generated by Django 3.0 on 2022-02-18 19:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Пошта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефону')),
                ('city', models.CharField(choices=[('L', 'Львів'), ('S', 'Стрий')], max_length=1, verbose_name='Місто')),
                ('street', models.CharField(max_length=100, verbose_name='Вулиця')),
                ('street_number', models.PositiveIntegerField(verbose_name='Номер вулиці')),
            ],
        ),
    ]
